# Generated by Django 2.2.7 on 2019-11-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('examiners', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('exam_start_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='In Minutes')),
                ('total_marks', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('on_venue', 'On venue'), ('online', 'Online')], default='online', max_length=15)),
                ('exam_location', models.TextField(blank=True, default=None, help_text='Required Only For On venue exams', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, default=None, help_text='This field is only required for questions with image', null=True, upload_to='EasyExam/images')),
                ('question_video', models.FileField(blank=True, default=None, help_text='This field is only required for questions with video', null=True, upload_to='EasyExam/videos')),
                ('question_audio', models.FileField(blank=True, default=None, help_text='This field is only required for questions with audio', null=True, upload_to='EasyExam/audios')),
                ('right_answer', models.CharField(max_length=200)),
                ('right_answer_condition', models.CharField(choices=[('exact', 'Answer must be exactly the same'), ('keyword', 'Answer must include keywords'), ('choice', 'Choose one or more correct answers')], default='choice', max_length=10)),
                ('right_answer_splitter', models.CharField(blank=True, default=',', help_text='This field is only required for choice and keyword conditions', max_length=10, null=True)),
                ('max_mark', models.IntegerField()),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('multi_text', 'Multiple Text'), ('single_choice', 'Choose One'), ('multiple_choice', 'Multiple Choice')], default='single_choice', max_length=50)),
                ('answer_descriptions', models.TextField(blank=True, default=None, help_text='Needed For Choice Answers.', null=True)),
                ('answer_values', models.CharField(blank=True, default=None, help_text='Required For Choice Answers. e.g (A/B/C/D)', max_length=10, null=True)),
                ('answer_choice_splitter', models.CharField(blank=True, default=',', help_text='This Field Is Used to Split Answers', max_length=10, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExam.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_id', models.IntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('registering_exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExam.ExamGroup')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExam.ExamGroup'),
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
                ('given_answer', models.TextField()),
                ('marks_achieved', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExam.Question')),
            ],
        ),
    ]
