# Generated by Django 2.2.7 on 2019-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyExam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinee',
            name='email',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='examinee',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='examinee',
            name='registering_exams',
        ),
        migrations.AddField(
            model_name='examinee',
            name='registering_exams',
            field=models.ManyToManyField(to='EasyExam.ExamGroup'),
        ),
    ]
