# Generated by Django 2.2.7 on 2019-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyExam', '0002_auto_20191125_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grading_standards',
            field=models.CharField(default='pass|>=|40', help_text='Standards for grading marks.\ne.g pass|>=|40, merit|>=|60, distinction|>=|80', max_length=250),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examiners',
            field=models.CharField(blank=True, default=None, help_text='Names of examiners if Exam is on venue', max_length=200, null=True),
        ),
    ]
