# Generated by Django 2.2.7 on 2019-11-28 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyExam', '0003_auto_20191127_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='examinee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EasyExam.Examinee'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grading_standards',
            field=models.CharField(default='pass:total_marks>=40', help_text='Standards for grading total marks. Format [grade]:total_marks>=[marks_to_achieve_grade]e.g Pass:total_marks>=40, Merit:total_marks>=60, Distinction:total_marks>=80', max_length=250),
        ),
    ]
